#!/bin/sh

# CHECK
# Run job, always return success for GitHub action
# Allows us to capture artifacts and test for success later
# Adds .github/workflows to PATH to shorten commands

echo "CHECK: ${*}"

WORKFLOWS=".github/workflows"

if [ ! -d $WORKFLOWS ]
then
  echo "CHECK: MISCONFIGURATION!"
  exit 1
fi

PATH=$WORKFLOWS:$PATH

# Run the arguments here!
if ! ${*}
then
  echo "CHECK FAILED: ${*}"
fi

# Always succeeds!
