name: Test Suite

env:
  # For Chicago time on log messages:
  TZ: CST6CDT

on:
  schedule:
    # Fire at 06:00 AM every day
    - cron: "0 6 * * *"
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build_conda_pkg:
    name: PY=${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Python
        run: |
          which python
          python --version

      - name: System basics
        run: |
          python .github/workflows/basics.py

      - name: Install NXinspect
        run: |
          pip install .

      - name: Show NXinspect
        run: |
          src/nxvalidate/scripts/nxinspect.py -v
