name: Test Suite

env:
  # For Chicago time on log messages:
  TZ: CST6CDT
  # Location of NXS files to generate and inspect:
  DATA: /tmp/test-data

on:
  schedule:
    # Fire at 06:00 AM every day
    - cron: "0 6 * * *"
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build_conda_pkg:
    name: PY=${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10" ] # , "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: System basics
        run: |
          which python
          python --version
          python .github/workflows/basics.py
          mkdir -pv $DATA

      - name: Install NXinspect
        run: |
          pip install --user .
          pip list    --user
          echo
          echo "Installed nxinspect:"
          ~/.local/bin/nxinspect -v

      - name: Test Chopper
        run: |
          wget -q -O $DATA/chopper.nxs https://github.com/nexpy/nexpy/raw/refs/heads/main/src/nexpy/examples/chopper.nxs
          ~/.local/bin/nxinspect -f $DATA/chopper.nxs

      - name: Test NeXpy Example
        run: |
          wget -q -O $DATA/example.nxs https://github.com/nexpy/nexpy/raw/refs/heads/main/src/nexpy/examples/example.nxs
          ~/.local/bin/nxinspect -f $DATA/example.nxs

      - name: Test 0001
        run: |
          python tests/0001-minimal.py
          .github/workflows/check ~/.local/bin/nxinspect -f $DATA/0001-minimal.nxs |& tee log
          echo "Checking error messages:"
          grep "class is NXentry" log

      - name: Test 0002
        run: |
          python tests/0002-root-save.py
          ~/.local/bin/nxinspect -f $DATA/0002-root-save.nxs

      - name: Test 0003
        run: |
          python tests/0003-nxopen-w.py
          ~/.local/bin/nxinspect -f $DATA/0003-nxopen-w.nxs

      - name: Test 0004
        run: |
          python tests/0004-root.py
          ~/.local/bin/nxinspect -f $DATA/0004-root.nxs -i |& tee log
          echo "Checking output messages:"
          grep "NXroot:" log
          grep "NXentry: /entry" log

      - name: Test 0005
        run: |
          python tests/0005-top-data.py
          ~/.local/bin/nxinspect -f $DATA/0005-top-data.nxs -i |& tee log
          echo "Checking error messages:"
          grep "NXdata is an invalid class in NXroot" log
